[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
overbid = "8y7t2oh2JyvYUBGKYKt5i1EGXtwEG17xPHJ3RmP9jHqi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
